### ISSUE TITLE
BSD trained checkpoints

### ISSUE THREAD

**Issue by Magauiya** [ljzycmd/VDTR#2]
Dear authors,

Thank you for sharing your code and paper. Where can I find the checkpoints of the VDTR trained on a real blur dataset (**BSD**)? I only noticed GoPro and DVD checkpoints. 

Sincerely,
Magauiya

**Comment by ljzycmd** [comment]
I will update the model pretrained on BSD.

**Comment by ljzycmd** [comment]
Hello, the checkpoints are available now.
