### ISSUE TITLE
About the test code

### ISSUE THREAD

**Issue by wgp666** [ljzycmd/VDTR#4]
Hi, when I use the testing script `python test.py ./configs/vdtr/vdtr_dvd.yaml $Checkpoint_path ` you provided for testing on the DVD dataset, only 300 images are de-blurred, but the test set for the DVD dataset has 1000 images. I wonder if your code can deblur each image when testing?

**Comment by ljzycmd** [comment]
You may add the item `sampling: n_c` into the validation config of the DVD dataset.

**Comment by wgp666** [comment]
Thank you!
