### ISSUE TITLE
How to test on custom video?

### ISSUE THREAD

**Issue by kwea123** [ljzycmd/VDTR#5]

**Comment by ljzycmd** [comment]
Hi @kwea123, you can test your video by constructing DVD- or GOPRO-like data structures without modifying the testing codes. Specifically, 1) you should extract frames from the video with `ffmepg` or `opencv`; 2) put these frames in the same data structure of DVD or GOPRO dataset (you should also put the input frames in the GT folder to avoid metric calculation error in the predefined test function).

Or, you can reimplement the inference codes to support only blurry frames input (referring to the implementation https://github.com/ljzycmd/SimDeblur/blob/494eedfe85f4c9406a9bdac578b25bab2e3aa558/simdeblur/engine/trainer.py#L360).

By the way, I will upload a version of the inference code.

**Comment by kwea123** [comment]
it seems that the `inference.py` in simdeblur has been in TODO state for two years... are you the only person that maintains the repo, and there aren't too many people who do research in this field? It is rather complicated for new people that just want to give a video and see the result.
Thank you for your effort in maintaining all the repos.
